services:
  meilisearch:
    image: getmeili/meilisearch:v1.36
    ports:
      - "${MEILISEARCH_PORT:-7700}:7700"
    volumes:
      - meilisearch_data:/meili_data
    environment:
      MEILI_ENV: ${MEILI_ENV:-development}
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY:-masterKey}

volumes:
  meilisearch_data:
